### ISSUE TITLE
src/build.bat is missing

### ISSUE THREAD

**Issue by Arun-Jayabalan** [theronic/chessmate#15]
could you please provide the src/build.bat ?

**Comment by theronic** [comment]
To build and run Chessmate (from project folder):

    javac -d ./target src/*.java
    cd target
    java Chess.Main

You need to be in the target path (or in any path at same level as images folder because images are [loaded from relative paths](https://github.com/theronic/chessmate/blob/master/src/Main.java#L737-L753): `../images/some-image.jpg`. Back then I didn't know about Java resources in the classpath. Should fix this.

If that works for you, I'll add a build.sh file to root and update README.

**Comment by Arun-Jayabalan** [comment]
Thank you. I am able to run now. But the board bg colour is not getting
loaded. Board background colour is always white for all the squares. Could
you help, please ??

**Comment by theronic** [comment]
Can you post a screenshot? It should look like this:

![image](https://user-images.githubusercontent.com/1011676/144193755-20ea303b-c72f-4857-933f-327d31bde55c.png)

If it looks like this, then you are in the wrong relative path for images:

![image](https://user-images.githubusercontent.com/1011676/144193853-fc653f4e-77af-4127-9e3c-4b618f2e9017.png)

**Comment by Arun-Jayabalan** [comment]
Here is My command :

~/Documents/Projects/Java-Chess-master/Chess1.4$ java -classpath
/Users/arun/Documents/Projects/Java-Chess-master/out/production/Chess1.4
main.Main

[image: Screenshot 2021-12-01 at 08.50.28.png]

**Comment by theronic** [comment]
Your comment does not show screenshot, but your folder structure needs to look like this:
- src/
  - Main.java
  - Chess.java
  - _etc._
- images/
  - alpha.gif
  - icon_config.gif
  - _etc._
- target _(created by javac)_
  - Main.class
  - Chess.class
  - _etc._

To run, you have to `cd` to the target path because images are loaded relatively at "../images/<name>.gif". If you are in another path, e.g. your home directory, it will look for images *one folder up*, which is why you have to be in `target` when you run `java Chess.Main`.

From the project folder (where src and images folder resides), try this exactly:

```
javac -d ./target src/*.java
cd target
java Chess.Main
```

**Comment by Arun-Jayabalan** [comment]
<img width="1161" alt="Screenshot 2021-12-01 at 08 50 28" src="https://user-images.githubusercontent.com/1597963/144218102-aa3b2f3e-b253-4fb0-afe6-34a81768d26a.png">

**Comment by Arun-Jayabalan** [comment]
<img width="236" alt="Screenshot 2021-12-01 at 10 31 53" src="https://user-images.githubusercontent.com/1597963/144218889-2268d279-57cc-430e-af12-4ae0b055dd97.png">

**Comment by Arun-Jayabalan** [comment]
The images are loaded fine. The application working., But only the colour is missing. Thank you for looking

**Comment by theronic** [comment]
Sure, no problem. Your version might be based on original Chessmate code, but seems to be a fork or very different project given the different folder structure and different piece images.

**Comment by Arun-Jayabalan** [comment]
Got it. Fantastic. It works . Thank you. I'll update the build.bat and build.sh soon
